import { Noto_Sans_KR } from 'next/font/google';

import Header from '@/common/components/header/Header';
import Footer from '@/common/components/footer/Footer';
import './globals.css';

import type { Metadata } from 'next';

const sans = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" className={sans.className}>
            <body className="flex w-full flex-col">
                <Header />
                <main className="mx-auto w-full max-w-screen-2xl grow">{children}</main>
                <Footer />
            </body>
        </html>
    );
}

//테일윈드 익스텐션 설치, 테일윈드 프리티어 설치
//테일윈드를 src 폴더에 전역으로 설치하기 위해 './src/**/*.{js,ts,jsx,tsx,mdx}', 적용
